### ISSUE TITLE
Unity2023 compile error

### ISSUE THREAD

**Issue by mjshin82** [jiaozi158/UnitySSReflectionURP#1]
Thanks for sharing your implementation. 
However, unlike the 2022 version, the following error occurs in the 2023 version.
Can you check please?

```
Shader error in 'Hidden/Lighting/ScreenSpaceReflection': redefinition of '_BlitTexture_TexelSize' at Assets/ScreenSpaceReflection/ScreenSpaceReflection.hlsl(27) (on metal)
```

**Comment by jiaozi158** [comment]
Hi, thanks for letting me know this issue. It should be fixed now.
